---
title: "ASA_mark"
author: "Loïc"
date: "2024-10-29"
output: html_document
---


Packages:
```{r}
library(GGally)
library(FactoMineR)
library(factoextra)
library(glmmTMB)
library(ggplot2)
library(MASS)
library(car)
library(ggeffects)
library(dplyr)
library(DHARMa)
```



Import et traitement des données:
```{r}
data = read.csv("data.csv",dec = ",", header = T)
data[,1] = as.factor(data[,1])
data[,2] = as.factor(data[,2])
data[,3] = as.factor(data[,3])
for (i in 4:ncol(data)){
  data[,i] <- gsub(",", ".", data[,i])
  data[,i] <- as.numeric(data[,i])
}


```


Corrélations entre variables:
```{r}
data_cor = data[,4:13]
ggpairs(data_cor) 
```

ACP des différentes variables
```{r}
data_ACP = data[,4:13] 
ACP = PCA(data_ACP)

fviz_pca_ind(ACP,
             geom.ind = "point",      # Utiliser des points pour les individus
             col.ind = data$Treatment, # Colorier selon la variable Treatment
             palette = "jco",         # Palette de couleurs (modifiable)
             addEllipses = TRUE,      # Ajouter des ellipses par groupe de traitement
             legend.title = "Traitement")

# En conservant seulement les variables les moins corrélées (OTM, Head_area, Head_DNA)
data_ACP2 = data[,c(4,6,13)]
ACP2 = PCA(data_ACP2)

fviz_pca_ind(ACP2,
             geom.ind = "point",      # Utiliser des points pour les individus
             col.ind = data$Treatment, # Colorier selon la variable Treatment
             palette = "jco",         # Palette de couleurs (modifiable)
             addEllipses = TRUE,      # Ajouter des ellipses par groupe de traitement
             legend.title = "Traitement")
```

Dotchart OTM avec couleur en fct du traitement
```{r}
classes = data$Treatment
couleurs = c("dodgerblue3", "firebrick", "darkorange", "forestgreen","pink")
couleurs_points = couleurs[classes]

dotchart(data$Olive_Tail_Moment, pch=16, col=couleurs_points, xlab="OTM")
legend("topright", legend=levels(classes), col=couleurs, pch=16)
```

Histogramme pour caractériser la loi de distribution de la réponse

```{r}
hist(data$Olive_Tail_Moment, breaks = 100)
```



GLMM avec différentes distributions
```{r}
## Avec loi gamma (zero inflated)
mod_zi_gamma = glmmTMB(
  Olive_Tail_Moment+1 ~ Treatment + (1 | ID/PIC), # OTM+1 pour éviter les négatifs, et effet aléatoire "photo" imbriqué dans "individu"
  family = ziGamma(link = "log"),  
  data = data
)
# Vérification des résidus
summary(mod_zi_gamma)
residuals <- residuals(mod_zi_gamma)
fitted_values <- fitted(mod_zi_gamma)
plot(fitted_values,residuals)

ggplot(data, aes(x = fitted_values, y = residuals, color = Treatment)) +
  geom_point(alpha = 0.6) +
  labs(x = "Valeurs Ajustées", y = "Résidus", color = "Traitement") +
  theme_minimal() +
  theme(legend.position = "right")

## Avec loi gamma
mod_gamma = glmmTMB(
  Olive_Tail_Moment+1 ~ Treatment + (1 | ID/PIC), # OTM+1 pour éviter les négatifs, et effet aléatoire "photo" imbriqué dans "individu"
  family = Gamma(link = "log"),  
  data = data
)
# Vérification des résidus
summary(mod_gamma)
residuals <- residuals(mod_gamma)
fitted_values <- fitted(mod_gamma)
plot(fitted_values,residuals)

ggplot(data, aes(x = fitted_values, y = residuals, color = Treatment)) +
  geom_point(alpha = 0.6) +
  labs(x = "Valeurs Ajustées", y = "Résidus", color = "Traitement") +
  theme_minimal() +
  theme(legend.position = "right")

## Avec log-normale
mod_log_normale = glmmTMB(
  log(Olive_Tail_Moment+1) ~ Treatment + (1 | ID/PIC), # OTM+1 pour éviter les négatifs, et effet aléatoire "photo" imbriqué dans "individu"
  data = data
)
# Vérification des résidus
summary(mod_log_normale)
residuals <- residuals(mod_log_normale)
fitted_values <- fitted(mod_log_normale)
plot(fitted_values,residuals)

ggplot(data, aes(x = fitted_values, y = residuals, color = Treatment)) +
  geom_point(alpha = 0.6) +
  labs(x = "Valeurs Ajustées", y = "Résidus", color = "Traitement") +
  theme_minimal() +
  theme(legend.position = "right")
```



Résidus vs. OTM
```{r}
plot(data$Olive_Tail_Moment,residuals)
```


```{r}
res_mod_log_normale <- resid(mod_log_normale)
hist(res_mod_log_normale, breaks = 100, main = "Histogramme des résidus")
res_mod_log_normale  <- simulateResiduals(fittedModel = mod_log_normale)
plot(res_mod_log_normale)
testOverdispersion(res_mod_log_normale)
```


Holm-adjusted Tukey's pairwise comparison (Fait par l'étude)
```{r}
detach("package:FactoMineR", unload = TRUE)
library(emmeans)
emmeans_result <- emmeans(mod_log_normale, pairwise ~ Treatment)
pairs(emmeans_result, adjust = "holm")
```

Verif AIC
```{r}
AIC(mod_gamma)
AIC(mod_log_normale)
AIC(mod_zi_gamma)
```

```{r}
head(data)
summary(mod_log_normale)

pred <- predict(mod_log_normale, newdata = data, type = "response", se.fit = TRUE)

# Ajouter les prédictions et les intervalles de confiance au DataFrame `data`
data$predicted_OTM <- pred$fit
data$conf.low <- pred$fit - 1.96 * pred$se.fit  # Limite inférieure de l'IC à 95%
data$conf.high <- pred$fit + 1.96 * pred$se.fit  # Limite supérieure de l'IC à 95%


data_summary <- data %>%
  group_by(Treatment) %>%
  summarise(
    mean_predicted_OTM = mean(predicted_OTM),
    conf.low = mean_predicted_OTM - 1.96 * sd(predicted_OTM) / sqrt(n()),
    conf.high = mean_predicted_OTM + 1.96 * sd(predicted_OTM) / sqrt(n())
  )

# Créer le graphique
ggplot(data_summary, aes(x = Treatment, y = mean_predicted_OTM, color = Treatment)) +
  geom_point(size = 3) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +
  labs(x = "Traitement", y = "Prédiction (log(OTM+1))", color = "Traitement") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(data_summary, aes(x = Treatment, y = mean_predicted_OTM, fill = Treatment)) +
  geom_bar(stat = "identity", position = "dodge", width = 0.6) +  # Barres pour chaque moyenne
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +  # Barres d'erreur
  labs(x = "Traitement", y = "Prédiction (log(OTM+1))", fill = "Traitement") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

